// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

type Session struct {
	ID           string
	RefreshToken string
	AccessToken  string
}

type SessionTracking struct {
	Latitude  float64
	Longitude float64
	Altitude  float64
	Time      string
	SessionID string
}
